### ISSUE TITLE
Text area on Firefox Developer

### ISSUE THREAD

**Issue by quangIO** [ducthienbui97/gitlicense#19]
![image](https://user-images.githubusercontent.com/13181907/31070212-0d59f3dc-a792-11e7-95b1-631bd4112c9f.png)

**Comment by ducthienbui97** [comment]
Can we make the text area (5em for example) much bigger then vertically align text inside??

**Comment by LuckehPickle** [comment]
I can see two reasons why this could be occurring.

1. The repo name is quite long, forcing it to wrap.
2. We're using the default monospace font, which is likely different on different browsers/machines.

Getting around this will actually require a redesign I think. I'm willing to take it on if no one else has.

**Comment by LuckehPickle** [comment]
I've got a solution, but I'm going to wait for pull request #20 to merge or be closed, as I need to make some conflicting changes.

I made it so that the height of the text area automatically adapts to it's content. This means the font and the length of the name no longer matters. It looks like this: ![Automati textarea height](https://i.imgur.com/jO9aWwa.png).

**Comment by ducthienbui97** [comment]
@LuckehPickle  unless you use the change from #20 , there's no need to wait for it.
